routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

// AUTH ROUTES
Route::get('login', 'AuthController@showLoginForm')->name('login');
Route::post('login', 'AuthController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'AuthController@showLoginForm')->name('register');
Route::post('register', 'AuthController@register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
//AUTH ROUTES END

Route::group(['prefix'=>'dashboard','middleware'=>['auth','payed']], function(){
    Route::get('/','DashboardController@index');
    Route::resource('projects','ProjectController');
    Route::resource('tasks','TaskController')->only('store');
    Route::resource('team','TeamController')->only('index','store');
    Route::delete('team/{user}','TeamController@destroy');
    Route::resource('timeframes','TimeframeController')->except('index','show','create','edit');
    Route::delete('invite/{invite}','TeamController@destroy_invite');
});

Route::group(['prefix'=>'admin','middleware'=>['auth','locale'],'namespace'=>'Admin'], function(){
    Route::resource('timeframes','TimeFrameController');
});

Route::get('/invite/{mailhash}/{action}','TeamController@handleInvitation')->middleware('auth');
Route::get('payment','PaymentController@index');
Route::post('subscription/{plan}','PaymentController@subscription');

Route::get('setLocale/{locale}','HomeController@setLocale');

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    protected $fillable = ['owner_id'];

    public function members(){
        return $this->belongsToMany(User::class);
    }

    public function clients(){
        return $this->hasMany(Client::class);
    }

    public function projects(){
        return $this->hasMany(Project::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Cashier\Billable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'subscription_period_start', 'subscription_period_end'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile(){
        return $this->hasOne(Profile::class);
    }

    public function own_team(){
        return $this->hasOne(Team::class, 'owner_id','id');
    }

    public function teams(){
        return $this->belongsToMany(Team::class);
    }

    public function getFullNameAttribute(){
        return $this->profile->firstname . " " . $this->profile->lastname;
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Team;
use App\Models\Invite;
use Illuminate\Http\Request;

class TeamController extends Controller
{
    public function index(){
        $invitations = Invite::where('team_id','=',auth()->user()->own_team->id)->get();
        return view('team.index', compact('invitations'));
    }

    public function store(Request $request){
        $request->validate([
            'email'=>'required|email'
        ]);
        $user = User::select('id','email')->where('email','=',$request->email)->first();
        if(!$user){
            $user = new \stdClass();
            $user->email = $request->email;
        }
        $mailhash = $this->createHash(40);
        $invite = Invite::create([
            'user_id'=> isset($user->id) ? $user->id : NULL,
            'team_id'=>auth()->user()->own_team->id,
            'email'=> $user->email,
            'hash'=>$mailhash
        ]);
        event(new \App\Events\AddMemberToTeam($user, $mailhash));

        // TODO : Return SUCCESS
    }

    private function createHash($qty){
        $hash = [];
        $alphas = array_merge(range('A', 'Z'), range('a', 'z'), range(0,9));
        for($i=0;$i<$qty;$i+=1){
            $hash[] = $alphas[rand(0,count($alphas) - 1)];
        }
        return implode("", $hash);
    }

    public function handleInvitation($mailhash, $action){
        $invite = Invite::where('hash','=',$mailhash)->first();
        if($invite){
            $this->makeInvite($invite, $action);
        }else{
            abort('403');
        }
        return redirect('/');
    }

    private function makeInvite(Invite $invite, $action){
        if ($action == "accept") {
            if($invite->user_id) {
                $user = $invite->user_id;
            }else{
                $u = User::where('email','=',$invite->email)->first();
                $user = $u ? $u->id : NULL;
            }
            if($user){
                $team = Team::find($invite->team_id);
                $team->members()->attach($user);
                $invite->destroy($invite->id);
            }
        }
    }

    public function destroy(User $user){
        if(auth()->user()->own_team->members()->detach($user->id)){
            return redirect()->back();
        }
    }

    public function destroy_invite(Invite $invite){
        if(Invite::destroy($invite->id)){
            return redirect()->back();
        }
    }
}

resources/views/team/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <add-team-member></add-team-member>
                </div>
                <h2>{{__('My team')}}</h2>
                <div class="clearfix"></div>
                <br>
                <div class="card">
                    <div class="card-body">
                        @if(auth()->user()->has('teams'))
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>{{__('User')}}</th>
                                    <th>{{__('Date')}}</th>
                                    <th>{{__('Status')}}</th>
                                    <th></th>
                                </tr>
                                @foreach(auth()->user()->own_team->members as $member)
                                    @if(auth()->user()->id != $member->id)
                                        <tr>
                                            <td>{{ $member->full_name }}</td>
                                            <td>{{ $member->created_at->diffForHumans() }}</td>
                                            <td><div class="badge badge-success">{{__('Member')}}</div></td>
                                            <td>
                                                <form style="display: inline-block" method="post" action="/dashboard/team/{{ $member->id }}">
                                                    {{ method_field('DELETE') }}
                                                    @csrf
                                                    <button class="btn btn-danger btn-sm">
                                                        <ion-icon name="trash"></ion-icon>
                                                    </button>
                                                </form>

                                            </td>
                                        </tr>
                                    @endif
                                @endforeach
                            </table>
                        @endif
                    </div>
                </div>
                <br>
                <div class="card">
                    <div class="card-body">
                        <h3>{{__('Pending invites')}}</h3>
                        @if($invitations->count())
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>{{__('User')}}</th>
                                    <th>{{__('Date')}}</th>
                                    <th>{{__('Status')}}</th>
                                    <th></th>
                                </tr>
                                @foreach($invitations as $invitation)
                                    <tr>
                                         <td>@if($invitation->user) {{ $invitation->user->full_name }} @else {{ $invitation->email }} @endif</td>
                                        <td>{{ $invitation->created_at->diffForHumans() }}</td>
                                        <td><div class="badge badge-info">{{__('Pending')}}</div></td>
                                        <td>
                                            <form style="display: inline-block" method="post" action="/dashboard/invite/{{ $invitation->id }}">
                                                {{ method_field('DELETE') }}
                                                @csrf
                                                <button class="btn btn-danger btn-sm">
                                                    <ion-icon name="trash"></ion-icon>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection